source "https://rubygems.org"

gem "sinatra", "~> 4.0"
gem "puma", "~> 6.0"
gem "toml-rb", "~> 4.0"
gem "nokogiri", "~> 1.16"

group :development, :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
  gem "rerun", "~> 0.14"
end
