/**
 * Transparency log integrity (SIGNATIF Phase 3): consistency proofs,
 * signed tree heads, and fork detection.
 *
 * Mirrors oiml-pki-server/lib/oiml_pki/transparency_publisher.rb —
 * proofs generated by the Ruby log verify here in the browser.
 *
 * - verifyConsistency: RFC 6962 §2.1.4.2, leaves-known form. The
 *   verifier supplies the leaf hashes it holds (or fetched from the
 *   published leaf/<seq> files); the old and new heads are recomputed
 *   from the leaves plus the proof path. This is the strongest form:
 *   it re-derives both roots rather than trusting either.
 * - verifySignedHead: the log operator signs each tree head
 *   (ECDSA P-256, SHA-256, over the canonical head string) so proof
 *   material can be trusted without trusting the transport.
 * - detectFork: two signed heads at the same tree size with different
 *   roots is evidence of log misbehavior (the gossip invariant).
 */

import { toHex, fromHex } from "../shared/hex.ts";
import { base64ToBytes } from "../shared/base64.ts";
import { encodeText } from "../shared/crypto.ts";
import { sha256 } from "./transparency.ts";

export { sha256 };

export interface SignedTreeHead {
  size: number;
  /** Tree root hash. */
  root: string;
  timestamp: string;
  operator: string;
  /** P-1363 raw r||s hex signature over headString(). */
  signature?: string;
  /** SPKI PEM of the operator's public key. */
  public_key?: string;
}

/** The canonical byte string covered by a tree-head signature. */
export function headString(head: SignedTreeHead): string {
  return `CNML-TLOG-HEAD-v1|${head.operator}|${head.size}|${head.root}|${head.timestamp}`;
}

async function hashInternal(left: Uint8Array, right: Uint8Array): Promise<Uint8Array> {
  const buf = new Uint8Array(1 + left.length + right.length);
  buf[0] = 0x02;
  buf.set(left, 1);
  buf.set(right, 1 + left.length);
  return sha256(buf);
}

function constantTimeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

function largestPow2Lt(n: number): number {
  return 1 << Math.floor(Math.log2(n - 1));
}

/** MTH of a list of already-leaf-hashed nodes (RFC 6962 tree shape). */
async function rootOf(nodes: Uint8Array[]): Promise<Uint8Array> {
  let level = nodes;
  while (level.length > 1) {
    const next: Uint8Array[] = [];
    for (let i = 0; i < level.length; i += 2) {
      next.push(i + 1 < level.length ? await hashInternal(level[i], level[i + 1]) : level[i]);
    }
    level = next;
  }
  return level[0];
}

type Subverify = [ok: boolean, rest: Uint8Array[], oldHash: Uint8Array | null, newHash: Uint8Array | null];

async function subverify(m: number, leaves: Uint8Array[], proof: Uint8Array[], b: boolean): Promise<Subverify> {
  const n = leaves.length;
  if (m === n) {
    const h = await rootOf(leaves);
    if (b) return [true, proof, h, h];
    if (proof.length === 0 || !constantTimeEqual(proof[0], h)) return [false, proof, null, null];
    return [true, proof.slice(1), h, h];
  }
  const k = largestPow2Lt(n);
  if (m <= k) {
    const [ok, rest, oldHash, newHash] = await subverify(m, leaves.slice(0, k), proof, b);
    if (!ok || rest.length === 0) return [false, rest, null, null];
    return [true, rest.slice(1), oldHash, await hashInternal(newHash!, rest[0])];
  }
  const [ok, rest, oldHash, newHash] = await subverify(m - k, leaves.slice(k), proof, false);
  if (!ok || rest.length === 0) return [false, rest, null, null];
  const leftHash = rest[0];
  return [
    true,
    rest.slice(1),
    await hashInternal(leftHash, oldHash!),
    await hashInternal(leftHash, newHash!),
  ];
}

/**
 * Verify an RFC 6962 consistency proof between two tree heads.
 *
 * @param oldSize size of the earlier head
 * @param newSize size of the later head
 * @param nodes proof node hashes (hex or bytes)
 * @param leafHashes the leaf hashes of the NEW tree (already leaf-hashed
 *        per RFC 6962: SHA-256(0x01 || entry))
 * @param oldRoot hex root claimed by the earlier signed head
 * @param newRoot hex root claimed by the later signed head
 */
export async function verifyConsistency(
  oldSize: number,
  newSize: number,
  nodes: (string | Uint8Array)[],
  leafHashes: (string | Uint8Array)[],
  oldRoot: string,
  newRoot: string,
): Promise<boolean> {
  if (oldSize < 0 || oldSize > newSize || newSize > leafHashes.length) return false;
  const proof = nodes.map((n) => (typeof n === "string" ? fromHex(n) : n));
  const leaves = leafHashes.map((l) => (typeof l === "string" ? fromHex(l) : l));
  const old = fromHex(oldRoot);
  const nw = fromHex(newRoot);

  if (oldSize === 0) return proof.length === 0;
  if (oldSize === newSize) return proof.length === 0 && constantTimeEqual(old, nw);
  if (proof.length === 0) return false;

  const [ok, rest, oldHash, newHash] = await subverify(oldSize, leaves.slice(0, newSize), proof, true);
  return ok
    && rest.length === 0
    && oldHash !== null && constantTimeEqual(oldHash, old)
    && newHash !== null && constantTimeEqual(newHash, nw);
}

/** Hash a log entry (raw cert hash) into an RFC 6962 leaf hash. */
export async function leafHashOf(entry: Uint8Array | string): Promise<Uint8Array> {
  const data = typeof entry === "string" ? encodeText(entry) : entry;
  const buf = new Uint8Array(1 + data.length);
  buf[0] = 0x01;
  buf.set(data, 1);
  return sha256(buf);
}

/** Compute the tree root over a list of raw entries (helper for tests/mirrors). */
export async function rootOverEntries(entries: (Uint8Array | string)[]): Promise<string> {
  const leaves: Uint8Array[] = [];
  for (const e of entries) leaves.push(await leafHashOf(e));
  return toHex(await rootOf(leaves));
}

function pemToBytes(pem: string): Uint8Array {
  const b64 = pem.replace(/-----BEGIN [A-Z0-9 ]+-----/g, "").replace(/-----END [A-Z0-9 ]+-----/g, "").replace(/\s+/g, "");
  return base64ToBytes(b64);
}

/**
 * Verify an operator's signature over a tree head.
 *
 * @param head the signed head (signature hex, P-1363 r||s)
 * @param key optional CryptoKey (ECDSA P-256); derived from
 *        head.public_key PEM when omitted
 */
export async function verifySignedHead(
  head: SignedTreeHead,
  key?: CryptoKey,
): Promise<boolean> {
  if (!head.signature) return false;
  let verifyKey = key;
  if (!verifyKey) {
    if (!head.public_key) return false;
    verifyKey = await crypto.subtle.importKey(
      "spki",
      pemToBytes(head.public_key),
      { name: "ECDSA", namedCurve: "P-256" },
      true,
      ["verify"],
    );
  }
  const sig = fromHex(head.signature);
  return crypto.subtle.verify(
    { name: "ECDSA", hash: "SHA-256" },
    verifyKey,
    sig,
    encodeText(headString(head)),
  );
}

/**
 * Gossip invariant: among signed heads at the same tree size, at most
 * one distinct root may exist. Two different roots at one size is
 * proof of misbehavior (a log fork).
 */
export function detectFork(heads: SignedTreeHead[]): { fork: boolean; conflicting: SignedTreeHead[] } {
  const bySize = new Map<number, Map<string, SignedTreeHead>>();
  for (const h of heads) {
    let roots = bySize.get(h.size) ?? new Map<string, SignedTreeHead>();
    roots.set(h.root, h);
    bySize.set(h.size, roots);
  }
  for (const roots of bySize.values()) {
    if (roots.size > 1) {
      return { fork: true, conflicting: [...roots.values()] };
    }
  }
  return { fork: false, conflicting: [] };
}
