/**
 * Tests for transparency-consistency.ts (SIGNATIF Phase 3).
 *
 * The fixture is generated by the Ruby TransparencyPublisher
 * (oiml-pki-server), so passing tests prove cross-language agreement:
 * proofs and signed heads produced by the CA log verify in the
 * browser verifier.
 */

import "./_test-polyfill.ts";

import { test } from "node:test";
import assert from "node:assert/strict";
import fixture from "./__fixtures__/consistency.json" with { type: "json" };
import {
  verifyConsistency,
  verifyConsistencyHeads,
  verifySignedHead,
  detectFork,
  gossipQuorumMet,
  multiLogQuorumMet,
  headString,
  leafHashOf,
  rootOverEntries,
  type SignedTreeHead,
} from "./transparency-consistency.ts";
import { fromHex } from "../shared/hex.ts";

const ENTRIES = fixture.entries_hex.map((h: string) => fromHex(h));
const ROOTS = fixture.roots as string[];

async function leafHashes(): Promise<Uint8Array[]> {
  const out: Uint8Array[] = [];
  for (const e of ENTRIES) out.push(await leafHashOf(e));
  return out;
}

test("TS root computation agrees with the Ruby log", async () => {
  for (let size = 1; size <= 5; size++) {
    const root = await rootOverEntries(ENTRIES.slice(0, size));
    assert.equal(root, ROOTS[size], `size ${size}`);
  }
});

test("Ruby-generated consistency proofs verify in TS", async () => {
  const leaves = await leafHashes();
  for (const p of fixture.proofs as { old_size: number; new_size: number; nodes: string[] }[]) {
    const ok = await verifyConsistency(
      p.old_size,
      p.new_size,
      p.nodes,
      leaves,
      ROOTS[p.old_size],
      ROOTS[p.new_size],
    );
    assert.equal(ok, true, `old=${p.old_size} new=${p.new_size}`);
  }
});

test("doctored consistency nodes are rejected", async () => {
  const leaves = await leafHashes();
  const p = fixture.proofs[1]; // old=2 new=5
  const doctored = p.nodes.slice();
  doctored[0] = "ab".repeat(32);
  const ok = await verifyConsistency(p.old_size, p.new_size, doctored, leaves, ROOTS[p.old_size], ROOTS[p.new_size]);
  assert.equal(ok, false);
});

test("wrong old root is rejected", async () => {
  const leaves = await leafHashes();
  const p = fixture.proofs[1];
  const ok = await verifyConsistency(
    p.old_size, p.new_size, p.nodes, leaves,
    ROOTS[p.old_size + 1], // claim the wrong old head
    ROOTS[p.new_size],
  );
  assert.equal(ok, false);
});

test("Ruby-signed tree head verifies in TS", async () => {
  const ok = await verifySignedHead(fixture.head as unknown as SignedTreeHead);
  assert.equal(ok, true);
});

test("tampered tree head signature is rejected", async () => {
  const head = { ...(fixture.head as unknown as SignedTreeHead) };
  head.size = (head.size as number) + 1;
  const ok = await verifySignedHead(head);
  assert.equal(ok, false);
});

test("headString canonical form is stable", () => {
  const head = fixture.head as unknown as SignedTreeHead;
  assert.equal(
    headString(head),
    `CNML-TLOG-HEAD-v1|${head.operator}|${head.size}|${head.root}|${head.timestamp}`,
  );
});

test("detectFork flags two roots at one size", () => {
  const a = { size: 5, root: ROOTS[5], timestamp: "t1", operator: "BIML" };
  const b = { size: 5, root: ROOTS[4], timestamp: "t2", operator: "BIML" };
  const c = { size: 6, root: ROOTS[4], timestamp: "t3", operator: "BIML" };
  const r = detectFork([a, b, c]);
  assert.equal(r.fork, true);
  assert.equal(r.conflicting.length, 2);
});

test("detectFork passes on an honest head sequence", () => {
  const heads = [1, 2, 3, 4, 5].map((size) => ({
    size, root: ROOTS[size], timestamp: `t${size}`, operator: "BIML",
  }));
  const r = detectFork(heads);
  assert.equal(r.fork, false);
});


test("leafless head-to-head verification matches the leaves-known form", async () => {
  for (const p of fixture.proofs as { old_size: number; new_size: number; nodes: string[] }[]) {
    const ok = await verifyConsistencyHeads(
      p.old_size,
      ROOTS[p.old_size],
      p.new_size,
      ROOTS[p.new_size],
      p.nodes,
    );
    assert.equal(ok, true, `old=${p.old_size} new=${p.new_size}`);
  }
});

test("leafless verification rejects doctored nodes and wrong heads", async () => {
  const p = fixture.proofs[2]; // old=3 new=5
  const doctored = p.nodes.slice();
  doctored[0] = "cd".repeat(32);
  assert.equal(
    await verifyConsistencyHeads(p.old_size, ROOTS[p.old_size], p.new_size, ROOTS[p.new_size], doctored),
    false,
  );
  assert.equal(
    await verifyConsistencyHeads(p.old_size, ROOTS[p.old_size + 1], p.new_size, ROOTS[p.new_size], p.nodes),
    false,
  );
  assert.equal(
    await verifyConsistencyHeads(p.old_size, ROOTS[p.old_size], p.new_size, ROOTS[p.new_size], p.nodes.slice(0, 1)),
    false,
  );
});


test("gossip quorum requires t independent agreeing sources", () => {
  const head = { size: 5, root: ROOTS[5], timestamp: "t1", operator: "BIML" };
  const other = { size: 5, root: ROOTS[4], timestamp: "t2", operator: "BIML" };
  const obs = (source: string, h: unknown) => ({ source, head: h as SignedTreeHead });

  const one = gossipQuorumMet([obs("mirror-a", head)], head);
  assert.equal(one.met, false);

  const two = gossipQuorumMet([obs("mirror-a", head), obs("mirror-b", head), obs("mirror-c", other)], head);
  assert.equal(two.met, true);
  assert.deepEqual(two.sources.sort(), ["mirror-a", "mirror-b"]);

  const three = gossipQuorumMet(
    [obs("a", head), obs("b", other), obs("c", other), obs("d", other)],
    head,
    { t: 3 },
  );
  assert.equal(three.met, false);
});

test("multi-log quorum requires m of k recognized logs", () => {
  const policy = { m: 2, k: 3, logs: ["log-a", "log-b", "log-c"] };
  const ok = multiLogQuorumMet(
    [
      { log: "log-a", verified: true },
      { log: "log-b", verified: true },
      { log: "log-c", verified: false },
    ],
    policy,
  );
  assert.equal(ok.met, true);
  assert.equal(ok.count, 2);

  const notEnough = multiLogQuorumMet(
    [
      { log: "log-a", verified: true },
      { log: "log-c", verified: false },
    ],
    policy,
  );
  assert.equal(notEnough.met, false);

  // Unrecognized logs never count.
  const unrecognized = multiLogQuorumMet(
    [
      { log: "log-a", verified: true },
      { log: "stranger", verified: true },
    ],
    policy,
  );
  assert.equal(unrecognized.met, false);
});
