/**
 * @oiml/cnml-schemas — full schema stack for OIML CNML web app.
 *
 * AUTO-GENERATED by scripts/generate-schemas-index.ts — DO NOT EDIT.
 * To add a Recommendation: drop schemas/R<NN>.yaml with x-oiml-* metadata
 * and re-run `pnpm gen:schemas`.
 *
 * Includes:
 *   - Core OIML certificate model (_core.yaml)
 *   - UnitsDB enums (_units.yaml) and OIML-local compound units (_units_local.yaml)
 *   - Shared modules (D 11 environmental, etc.)
 *   - 22 per-Recommendation schemas, auto-discovered from schemas/
 *   - Sample cert YAMLs for round-trip testing
 *
 * All schemas are JSON Schema draft-07.
 */
import core from "./_core.yaml";
import units from "./_units.yaml";
import unitsLocal from "./_units_local.yaml";
import d011Env from "./modules/d011_environmental.yaml";

import r21 from "./schemas/R21.yaml";
import r31 from "./schemas/R31.yaml";
import r46 from "./schemas/R46.yaml";
import r49 from "./schemas/R49.yaml";
import r50 from "./schemas/R50.yaml";
import r51 from "./schemas/R51.yaml";
import r60 from "./schemas/R60.yaml";
import r61 from "./schemas/R61.yaml";
import r76 from "./schemas/R76.yaml";
import r85 from "./schemas/R85.yaml";
import r99 from "./schemas/R99.yaml";
import r105 from "./schemas/R105.yaml";
import r106 from "./schemas/R106.yaml";
import r107 from "./schemas/R107.yaml";
import r111 from "./schemas/R111.yaml";
import r117 from "./schemas/R117.yaml";
import r126 from "./schemas/R126.yaml";
import r129 from "./schemas/R129.yaml";
import r134 from "./schemas/R134.yaml";
import r136 from "./schemas/R136.yaml";
import r137 from "./schemas/R137.yaml";
import r139 from "./schemas/R139.yaml";

export const CORE = core;
export const UNITS = units;
export const UNITS_LOCAL = unitsLocal;
export const MODULES = { d011_environmental: d011Env };

const SCHEMAS: Record<string, unknown> = {
  "R21": r21,
  "R31": r31,
  "R46": r46,
  "R49": r49,
  "R50": r50,
  "R51": r51,
  "R60": r60,
  "R61": r61,
  "R76": r76,
  "R85": r85,
  "R99": r99,
  "R105": r105,
  "R106": r106,
  "R107": r107,
  "R111": r111,
  "R117": r117,
  "R126": r126,
  "R129": r129,
  "R134": r134,
  "R136": r136,
  "R137": r137,
  "R139": r139,
};

export interface RecommendationMeta {
  id: string;
  title: string;
  shortTitle: string;
  category: string;
  certCount: number;
  schema: unknown;
}

export const RECOMMENDATIONS: RecommendationMeta[] = [
  { id: "R21", title: "OIML R21 (Taximeters) Certificate Schema", shortTitle: "Taximeters", category: "Other", certCount: 42, schema: SCHEMAS["R21"] },
  { id: "R31", title: "OIML R31 (Diaphragm gas meters) Certificate Schema", shortTitle: "Diaphragm gas meters", category: "Fuel & Flow", certCount: 39, schema: SCHEMAS["R31"] },
  { id: "R46", title: "OIML R46 (Active Electrical Energy Meters) Certificate Schema", shortTitle: "Active electrical energy meters", category: "Electricity", certCount: 98, schema: SCHEMAS["R46"] },
  { id: "R49", title: "OIML R49 (Water Meters) Certificate Schema", shortTitle: "Water meters for cold potable water", category: "Water & Liquid", certCount: 4, schema: SCHEMAS["R49"] },
  { id: "R50", title: "OIML R50 (Continuous Totalising Automatic Weighing Instruments) Certificate Schema", shortTitle: "Continuous totalizing automatic weighing", category: "Weighing", certCount: 5, schema: SCHEMAS["R50"] },
  { id: "R51", title: "OIML R51 (Automatic Catchweighing Instruments) Certificate Schema", shortTitle: "Automatic catchweighing instruments", category: "Weighing", certCount: 100, schema: SCHEMAS["R51"] },
  { id: "R60", title: "OIML R60 (Load Cells) Certificate Schema", shortTitle: "Load cells", category: "Weighing", certCount: 100, schema: SCHEMAS["R60"] },
  { id: "R61", title: "OIML R61 (Automatic gravimetric filling instruments) Certificate Schema", shortTitle: "Automatic gravimetric filling instruments", category: "Weighing", certCount: 12, schema: SCHEMAS["R61"] },
  { id: "R76", title: "OIML R76 (Non-automatic weighing instruments) Certificate Schema", shortTitle: "Non-automatic weighing instruments", category: "Weighing", certCount: 100, schema: SCHEMAS["R76"] },
  { id: "R85", title: "OIML R85 (Automatic level measuring instruments) Certificate Schema", shortTitle: "Automatic level gauges", category: "Length & Dimension", certCount: 99, schema: SCHEMAS["R85"] },
  { id: "R99", title: "OIML R99 (Breath Analyzers / Exhaust Gas Analyzers) Certificate Schema", shortTitle: "Breath alcohol analyzers", category: "Other", certCount: 2, schema: SCHEMAS["R99"] },
  { id: "R105", title: "OIML R105 (Direct Mass Flow Measurement) Certificate Schema", shortTitle: "Direct mass flow measuring systems", category: "Other", certCount: 1, schema: SCHEMAS["R105"] },
  { id: "R106", title: "OIML R106 (Automatic Rail-Weighbridges) Certificate Schema", shortTitle: "Automatic rail weighbridges", category: "Weighing", certCount: 3, schema: SCHEMAS["R106"] },
  { id: "R107", title: "OIML R107 (Discontinuous Totalizing Automatic Weighing Instruments) Certificate Schema", shortTitle: "Discontinuous totalizing instruments", category: "Weighing", certCount: 3, schema: SCHEMAS["R107"] },
  { id: "R111", title: "OIML R111 (Weights of Accuracy Classes E1, E2, F1, F2, M1, M2, M3) Certificate Schema", shortTitle: "Weights of accuracy classes E1..M3", category: "Weighing", certCount: 1, schema: SCHEMAS["R111"] },
  { id: "R117", title: "OIML R117 (Dynamic Measuring Systems for Liquids Other than Water) Certificate Schema", shortTitle: "Fuel dispensers (liquids other than water)", category: "Fuel & Flow", certCount: 85, schema: SCHEMAS["R117"] },
  { id: "R126", title: "OIML R126 (Evidential breath analyzers) Certificate Schema", shortTitle: "Evidential breath analyzers", category: "Other", certCount: 9, schema: SCHEMAS["R126"] },
  { id: "R129", title: "OIML R129 (Multidimensional Measuring Instruments) Certificate Schema", shortTitle: "Multidimensional measuring instruments", category: "Length & Dimension", certCount: 3, schema: SCHEMAS["R129"] },
  { id: "R134", title: "OIML R134 (Automatic instruments for weighing road vehicles in motion) Certificate Schema", shortTitle: "Automatic instruments for weighing road vehicles", category: "Weighing", certCount: 35, schema: SCHEMAS["R134"] },
  { id: "R136", title: "OIML R136 (Liquid Other Than Water — Density Measurement) Certificate Schema", shortTitle: "Liquid density measuring instruments", category: "Other", certCount: 1, schema: SCHEMAS["R136"] },
  { id: "R137", title: "OIML R137 (Dynamic Measuring Systems for Gases — Gas Meters) Certificate Schema", shortTitle: "Dynamic measuring systems for gas", category: "Fuel & Flow", certCount: 99, schema: SCHEMAS["R137"] },
  { id: "R139", title: "OIML R139 (Compressed gaseous fuel dispensers — CNG and hydrogen) Certificate Schema", shortTitle: "CNG & hydrogen dispensers", category: "Fuel & Flow", certCount: 39, schema: SCHEMAS["R139"] },
];

export function getRecommendation(id: string): RecommendationMeta | undefined {
  return RECOMMENDATIONS.find((r) => r.id === id.toUpperCase());
}
