/**
 * Glossary term auto-linking (TODO.cnml/45).
 *
 * Scans rendered docs HTML for mentions of glossary terms and wraps
 * each in an `<a>` tag pointing at the glossary anchor. The glossary
 * is parsed once at build time; the term registry is a JSON file
 * generated by `scripts/build-glossary.ts`.
 *
 * The linker skips:
 *   - `<code>` and `<pre>` (already-link or code contexts)
 *   - existing `<a>` link contexts
 *   - `<h1>` (the title)
 *
 * Plural and case variants are matched: "HSMs" links to "HSM", "frost"
 * links to "FROST" (case-insensitive search, original case in
 * display).
 *
 * A maximum of 3 occurrences per page per term avoids link spam.
 */

import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export interface GlossaryEntry {
  /** The term as it appears in the glossary (e.g., "FROST"). */
  term: string;
  /** The anchor on the glossary page (e.g., "FROST"). */
  anchor: string;
  /** Aliases that should also link to this entry. */
  aliases: string[];
}

let cachedRegistry: GlossaryEntry[] | null = null;

const MAX_OCCURRENCES_PER_TERM = 3;

/**
 * Build the term registry from a parsed glossary. Exported for
 * testing — production callers use `getGlossaryRegistry()` which
 * reads the cached JSON.
 */
export function buildRegistryFromGlossaryMarkdown(md: string): GlossaryEntry[] {
  const entries: GlossaryEntry[] = [];
  const lines = md.split("\n");
  let inBody = false;
  for (const line of lines) {
    if (line.startsWith("# ")) {
      inBody = true;
      continue;
    }
    if (!inBody) continue;
    // Glossary entries are `**Term.** Description`.
    const m = line.match(/^\*\*([^*]+?)\.\*\*\s+(.*)$/);
    if (!m) continue;
    const term = m[1]!.trim();
    entries.push({ term, anchor: slugify(term), aliases: [] });
  }
  return entries;
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^\w\s-]/g, "").replace(/\s+/g, "-");
}

/**
 * Load the cached registry. Falls back to an empty list when the
 * cache is missing (e.g., during a clean build before the
 * glossary-extraction script has run).
 */
export function getGlossaryRegistry(): GlossaryEntry[] {
  if (cachedRegistry) return cachedRegistry;
  const here = dirname(fileURLToPath(new URL(".", import.meta.url)));
  // The registry lives next to the glossary source. The path is
  // data/glossary-terms.json under apps/cnml-web/src/.
  const candidates = [
    join(here, "..", "data", "glossary-terms.json"),
    join(here, "..", "..", "src", "data", "glossary-terms.json"),
  ];
  for (const p of candidates) {
    if (existsSync(p)) {
      cachedRegistry = JSON.parse(readFileSync(p, "utf8")) as GlossaryEntry[];
      return cachedRegistry;
    }
  }
  cachedRegistry = [];
  return cachedRegistry;
}

/**
 * Link glossary term mentions in a rendered HTML body. Operates on
 * text nodes only — does not descend into `<code>`, `<pre>`, `<a>`,
 * or `<h1>` elements.
 */
export function linkGlossaryTerms(html: string, registry: GlossaryEntry[] = getGlossaryRegistry()): string {
  if (registry.length === 0) return html;

  // Build a single regex that matches any term. Longer terms are
  // matched first so "HSM" does not eat "HSM cluster".
  const sorted = [...registry].sort((a, b) => {
    const aLen = a.term.length + Math.max(0, ...a.aliases.map((x) => x.length));
    const bLen = b.term.length + Math.max(0, ...b.aliases.map((x) => x.length));
    return bLen - aLen;
  });

  // Walk the HTML and skip element-content for forbidden parents.
  // We tokenize by `<...>` tags so text outside tags is processed
  // and text inside `<code>`, `<pre>`, `<a>`, `<h1>` is left alone.
  const tokens = html.split(/(<[^>]+>)/);
  let forbiddenDepth = 0;
  const counts = new Map<string, number>();

  for (let i = 0; i < tokens.length; i++) {
    const tok = tokens[i]!;
    if (tok.startsWith("<")) {
      const lower = tok.toLowerCase();
      if (isOpeningForbidden(lower)) forbiddenDepth++;
      else if (isClosingForbidden(lower)) forbiddenDepth = Math.max(0, forbiddenDepth - 1);
      continue;
    }
    if (forbiddenDepth > 0) continue;

    tokens[i] = applyTermsToText(tok, sorted, counts);
  }
  return tokens.join("");
}

function isOpeningForbidden(tag: string): boolean {
  return /^<(code|pre|a|h1|script|style|kbd|samp)\b/.test(tag);
}
function isClosingForbidden(tag: string): boolean {
  return /^<\/(code|pre|a|h1|script|style|kbd|samp)\b/.test(tag);
}

function applyTermsToText(
  text: string,
  registry: GlossaryEntry[],
  counts: Map<string, number>,
): string {
  let out = text;
  for (const entry of registry) {
    const variants = [entry.term, ...entry.aliases].map(escapeRegex);
    if (variants.length === 0) continue;
    // Allow trailing "s" for plurals.
    const alternation = variants.join("|");
    const re = new RegExp(`\\b(${alternation})(s?)\\b`, "g");
    out = out.replace(re, (full, matched, plural) => {
      const key = entry.anchor;
      const n = counts.get(key) ?? 0;
      if (n >= MAX_OCCURRENCES_PER_TERM) return full;
      counts.set(key, n + 1);
      const href = `/cnml/docs/reference/glossary#${entry.anchor}`;
      return `<a href="${href}" class="cnml-glossary-link">${matched}${plural ?? ""}</a>`;
    });
  }
  return out;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
