/**
 * Generate packages/cnml-schemas/src/index.ts from schemas/R*.yaml.
 *
 * - Discovers every R*.yaml file in src/schemas/
 * - Pulls `x-oiml-category`, `x-oiml-short-title`, `x-oiml-cert-count` from each
 * - Falls back to the long `title` if x-oiml-short-title is missing
 * - Emits index.ts with one import per schema + a RECOMMENDATIONS array
 *   built from the metadata. No R-specific data is hand-maintained.
 *
 * The generated file is marked as such — do not edit by hand. To add a new
 * Recommendation, drop a new R<NN>.yaml into src/schemas/ with x-oiml-*
 * metadata and re-run `pnpm gen:schemas`.
 *
 * Run: pnpm gen:schemas
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_DIR = join(__dirname, "../packages/cnml-schemas/src/schemas");
const SRC_DIR    = join(__dirname, "../packages/cnml-schemas/src");
const OUT_FILE   = join(__dirname, "../packages/cnml-schemas/src/index.ts");
const OUT_NODE   = join(__dirname, "../packages/cnml-schemas/src/index.node.mjs");

interface SchemaMeta {
  filename: string;
  rId: string;
  title: string;
  shortTitle: string;
  category: string;
  certCount: number;
}

const files = readdirSync(SCHEMA_DIR)
  .filter((f) => /^R\d+\.yaml$/.test(f))
  .sort((a, b) => {
    const na = parseInt(a.replace(/^R(\d+)\.yaml$/, "$1"), 10);
    const nb = parseInt(b.replace(/^R(\d+)\.yaml$/, "$1"), 10);
    return na - nb;
  });

const metas: SchemaMeta[] = [];
for (const f of files) {
  const text = readFileSync(join(SCHEMA_DIR, f), "utf8");
  const data = yaml.parse(text);
  const rId = f.replace(/\.yaml$/, "");
  const shortTitle = data?.["x-oiml-short-title"]
    ?? data?.title?.match(/\(([^)]+)\)/)?.[1]
    ?? data?.title
    ?? rId;
  metas.push({
    filename: f,
    rId,
    title:        data?.title ?? rId,
    shortTitle,
    category:     data?.["x-oiml-category"] ?? "Uncategorised",
    certCount:    data?.["x-oiml-cert-count"] ?? 0,
  });
}

if (metas.length === 0) {
  console.error("No schemas found in", SCHEMA_DIR);
  process.exit(1);
}

// ─── Emit index.ts ────────────────────────────────────────────────────

const lines: string[] = [
  "/**",
  " * @oiml/cnml-schemas — full schema stack for OIML CNML web app.",
  " *",
  " * AUTO-GENERATED by scripts/generate-schemas-index.ts — DO NOT EDIT.",
  " * To add a Recommendation: drop schemas/R<NN>.yaml with x-oiml-* metadata",
  " * and re-run `pnpm gen:schemas`.",
  " *",
  " * Includes:",
  " *   - Core OIML certificate model (_core.yaml)",
  " *   - UnitsDB enums (_units.yaml) and OIML-local compound units (_units_local.yaml)",
  " *   - Shared modules (D 11 environmental, etc.)",
  ` *   - ${metas.length} per-Recommendation schemas, auto-discovered from schemas/`,
  " *   - Sample cert YAMLs for round-trip testing",
  " *",
  " * All schemas are JSON Schema draft-07.",
  " */",
  "import core from \"./_core.yaml\";",
  "import units from \"./_units.yaml\";",
  "import unitsLocal from \"./_units_local.yaml\";",
  "import d011Env from \"./modules/d011_environmental.yaml\";",
  "",
];

// One import per schema. Named as `rNN` (lowercase) — these are private,
// only used to populate the RECOMMENDATIONS array below. Consumers should
// use RECOMMENDATIONS / getRecommendation() instead.
for (const m of metas) {
  lines.push(`import ${m.rId.toLowerCase()} from "./schemas/${m.filename}";`);
}

lines.push("");
lines.push("export const CORE = core;");
lines.push("export const UNITS = units;");
lines.push("export const UNITS_LOCAL = unitsLocal;");
lines.push("export const MODULES = { d011_environmental: d011Env };");
lines.push("");

// Schema registry: ID → schema object. Consumers use getRecommendation(id).
lines.push("const SCHEMAS: Record<string, unknown> = {");
for (const m of metas) {
  lines.push(`  ${JSON.stringify(m.rId)}: ${m.rId.toLowerCase()},`);
}
lines.push("};");
lines.push("");

lines.push("export interface RecommendationMeta {");
lines.push("  id: string;");
lines.push("  title: string;");
lines.push("  shortTitle: string;");
lines.push("  category: string;");
lines.push("  certCount: number;");
lines.push("  schema: unknown;");
lines.push("}");
lines.push("");

lines.push("export const RECOMMENDATIONS: RecommendationMeta[] = [");
for (const m of metas) {
  lines.push(`  { id: ${JSON.stringify(m.rId)}, title: ${JSON.stringify(m.title)}, shortTitle: ${JSON.stringify(m.shortTitle)}, category: ${JSON.stringify(m.category)}, certCount: ${m.certCount}, schema: SCHEMAS[${JSON.stringify(m.rId)}] },`);
}
lines.push("];");
lines.push("");

lines.push("export function getRecommendation(id: string): RecommendationMeta | undefined {");
lines.push("  return RECOMMENDATIONS.find((r) => r.id === id.toUpperCase());");
lines.push("}");
lines.push("");

writeFileSync(OUT_FILE, lines.join("\n"));

// ─── Emit index.node.mjs ────────────────────────────────────────────────
// The node-loadable twin: the SAME schema objects inlined as JSON — no
// YAML imports (plain node can't parse them; the vite/Astro consumers use
// index.ts). The check pipeline self-registers the core schemas through
// this entry when the YAML-importing one is unavailable.
const loadYaml = (rel: string): unknown => yaml.parse(readFileSync(join(SRC_DIR, rel), "utf8"));
const nodeLines: string[] = [
  "/** AUTO-GENERATED by scripts/generate-schemas-index.ts — DO NOT EDIT.",
  " *  The node-loadable twin of index.ts (JSON literals, no YAML imports). */",
  "",
  `export const CORE = ${JSON.stringify(loadYaml("_core.yaml"), null, 1)};`,
  `export const UNITS = ${JSON.stringify(loadYaml("_units.yaml"), null, 1)};`,
  `export const UNITS_LOCAL = ${JSON.stringify(loadYaml("_units_local.yaml"), null, 1)};`,
  `export const MODULES = { d011_environmental: ${JSON.stringify(loadYaml("modules/d011_environmental.yaml"), null, 1)} };`,
  "",
  "const SCHEMAS = {",
];
for (const m of metas) {
  nodeLines.push(`  ${JSON.stringify(m.rId)}: ${JSON.stringify(loadYaml(`schemas/${m.filename}`), null, 1)},`);
}
nodeLines.push("};");
nodeLines.push("");
nodeLines.push("export const RECOMMENDATIONS = [");
for (const m of metas) {
  nodeLines.push(`  { id: ${JSON.stringify(m.rId)}, title: ${JSON.stringify(m.title)}, shortTitle: ${JSON.stringify(m.shortTitle)}, category: ${JSON.stringify(m.category)}, certCount: ${m.certCount}, schema: SCHEMAS[${JSON.stringify(m.rId)}] },`);
}
nodeLines.push("];");
nodeLines.push("");
nodeLines.push("export function getRecommendation(id) {");
nodeLines.push("  return RECOMMENDATIONS.find((r) => r.id === id.toUpperCase());");
nodeLines.push("}");
nodeLines.push("");

writeFileSync(OUT_NODE, nodeLines.join("\n"));

console.log(`✓ Wrote ${OUT_FILE}`);
console.log(`  ${metas.length} schemas discovered:`);
for (const m of metas) {
  console.log(`    ${m.rId}  ${m.shortTitle}  [${m.category}]  n=${m.certCount}`);
}
